steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "***************************************"
      echo "Currently on branch - ${BRANCH_NAME}"
      echo "***************************************"