steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "***************************************"
      echo "Currently on branch - ${BRANCH_NAME}"
      echo "***************************************"

##### Terraform init #####
- id: 'tf init'
  name: 'hashicorp/terraform:0.14.9'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      cd terraform/k8s
      terraform init

##### Terraform plan #####
- id: 'tf plan'
  name: 'hashicorp/terraform:0.14.9'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      cd terraform/k8s
      terraform plan